-- RUN THIS SQL IN YOUR SUPABASE SQL EDITOR TO SET UP THE DATABASE --

-- 1. Create Products Table
create table public.products (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  price numeric(10,2) not null,
  tag text,
  type text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Create Orders Table
create table public.orders (
  id bigint generated by default as identity primary key,
  customer text not null,
  plan_name text,
  type text default 'Subscription',
  status text default 'Pending',
  pressed_time text default 'Pending',
  rider text default 'Unassigned',
  eta text default 'Pending',
  phone text,
  location jsonb, -- Stores lat/lng/address
  cart_json jsonb, -- Stores full cart details
  total_price numeric(10,2),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Insert Initial Product Data (The Menu)
insert into public.products (title, description, price, tag, type) values
('Daily Core', 'Pineapple + Ginger', 15.00, 'Vitality', 'Signature'),
('Green Habit', 'Spinach + Apple + Cucumber', 18.00, 'Detox', 'Signature'),
('Recovery', 'Carrot + Orange + Lime', 20.00, 'Immunity', 'Signature'),
('Blood Sugar Balance', 'Bitter Leaf + Cucumber + Apple', 25.00, 'Health', 'Functional'),
('Office Focus', 'Pineapple + Turmeric + Ginger', 22.00, 'Energy', 'Functional'),
('Daily Starter', 'Any 1 Bottle of your choice', 10.00, 'Trial', 'Starter');

-- 4. Enable Row Level Security (RLS) - Recommended
alter table public.products enable row level security;
alter table public.orders enable row level security;

-- 5. Create Policies (Allow public read for products, insert for orders)
create policy "Public products are viewable by everyone." on public.products for select using (true);
create policy "Authenticated users can update products." on public.products for update using (auth.role() = 'authenticated');
create policy "Authenticated users can insert products." on public.products for insert with check (auth.role() = 'authenticated');

create policy "Anyone can create orders." on public.orders for insert with check (true);
create policy "Authenticated users can view orders." on public.orders for select using (auth.role() = 'authenticated');
create policy "Authenticated users can update orders." on public.orders for update using (auth.role() = 'authenticated');
